Repository peering-manager/peering-manager, pull requests merged in 2019-08, with the labels that each got.

#160 Add script to generate template documentation.
  .pre-commit-config.yaml
  docs/templates/index.md
  docs/templates/objects/autonomoussystem.md
  docs/templates/objects/bgpgroup.md
  docs/templates/objects/community.md
  docs/templates/objects/directpeeringsession.md
  docs/templates/objects/internetexchange.md
  docs/templates/objects/internetexchangepeeringsession.md
  docs/templates/objects/router.md
  docs/templates/objects/routingpolicy.md
  scripts/documentation/generate_template_doc.py
Labels: documentation

#164 Fix for issue #158 where changelog shows funny on windows pcs
  project-static/css/base.css
Labels: bug

#163 Tagging system for objects
  docs/templates/objects/autonomoussystem.md
  docs/templates/objects/bgpgroup.md
  docs/templates/objects/community.md
  docs/templates/objects/directpeeringsession.md
  docs/templates/objects/internetexchange.md
  docs/templates/objects/internetexchangepeeringsession.md
  docs/templates/objects/router.md
  docs/templates/objects/routingpolicy.md
  peering/api/serializers.py
  peering/filters.py
  peering/forms.py
  peering/migrations/0050_auto_20190806_2159.py
  peering/models.py
  peering_manager/settings.py
  requirements.txt
  scripts/documentation/generate_template_doc.py
  templates/peering/as/add_edit.html
  templates/peering/as/details.html
  templates/peering/bgp-group/add_edit.html
  templates/peering/bgp-group/details.html
  templates/peering/community/add_edit.html
  templates/peering/community/details.html
  templates/peering/ix/add_edit.html
  templates/peering/ix/details.html
  templates/peering/router/add_edit.html
  templates/peering/router/details.html
  templates/peering/routing-policy/add_edit.html
  templates/peering/routing-policy/details.html
  templates/peering/session/direct/add_edit.html
  templates/peering/session/direct/details.html
  templates/peering/session/internet_exchange/add_edit.html
  templates/peering/session/internet_exchange/details.html
  templates/peering/template/add_edit.html
  templates/peering/template/details.html
  templates/utils/includes/tags_card.html
  templates/utils/templatetags/tag.html
  utils/filters.py
  utils/models.py
  utils/templatetags/helpers.py
Labels: feature request

#167 docs: fix missing codeblock
  docs/templates/cisco-iosxr.md
Labels: documentation
