Repository peering-manager/peering-manager, pull requests merged in 2020-04, with the labels that each got.

#225 Fix default timezone
  docs/configuration/optional-settings.md
  peering_manager/settings.py
Labels: type: enhancement

#229 Radius support
  .gitignore
  peering_manager/settings.py
  requirements_dev.txt
  requirements_radius.txt
Labels: type: feature request

#232 Fix list comparison in find_potential_ix_peering_sessions()
  peering/models.py
Labels: type: bug

#234 Update arista-eos Template in docs
  docs/templates/arista-eos.md
Labels: type: documentation

#230 Rest api enhancements
  peering/api/serializers.py
  peeringdb/api/serializers.py
  peeringdb/api/urls.py
  peeringdb/api/views.py
  peeringdb/filters.py
Labels: type: enhancement

#241 Some tweaks to improve to_dict() perf
  peering/models.py
  utils/models.py
Labels: type: enhancement

#231 New feature to allow building missing sessions for an AS
  peering/models.py
  peering/urls.py
  peering/views.py
  peeringdb/tables.py
  templates/peering/as/_base.html
  templates/peering/as/peers.html
Labels: type: feature request
