Repository peering-manager/peering-manager, pull requests merged in 2020-07, with the labels that each got.

#260 Background tasks using Redis
  docs/configuration/index.md
  docs/configuration/optional-settings.md
  docs/configuration/required-settings.md
  docs/setup/2-peering-manager.md
  docs/setup/3-web-server.md
  docs/setup/migrate-to-systemd.md
  docs/templates/objects/router.md
  peering/__init__.py
  peering/admin.py
  peering/api/serializers.py
  peering/api/views.py
  peering/apps.py
  peering/filters.py
  peering/migrations/0059_router_last_deployment_id.py
  peering/models.py
  peering/signals.py
  peering/tables.py
  peering/tests/test_views.py
  peering_manager/admin.py
  peering_manager/configuration.example.py
  peering_manager/releases.py
  peering_manager/settings.py
  peering_manager/tests/__init__.py
  peering_manager/tests/test_releases.py
  peering_manager/tests/test_views.py
  peering_manager/urls.py
  peering_manager/views.py
  project-static/js/base.js
  requirements.txt
  templates/_base.html
  templates/admin/index.html
  templates/home.html
  templates/peering/router/inc/routers_table.html
  templates/peering/router/list.html
  users/admin.py
  utils/api/__init__.py
  utils/functions.py
  utils/management/commands/__init__.py
  utils/management/commands/rqworker.py
  utils/middleware.py
  utils/migrations/0006_auto_20200626_2340.py
  webhooks/__init__.py
  webhooks/admin.py
  webhooks/apps.py
  webhooks/constants.py
  webhooks/management/__init__.py
  webhooks/management/commands/__init__.py
  webhooks/management/commands/webhook_receiver.py
  webhooks/migrations/0001_initial.py
  webhooks/migrations/__init__.py
  webhooks/models.py
  webhooks/tests/__init__.py
  webhooks/tests/test_webhooks.py
  webhooks/workers.py
Labels: type: feature request

#266 Fix router ix session count
  peering/views.py
Labels: type: bug

#267 Add Redis documentation
  docs/setup/2-redis.md
  docs/setup/3-peering-manager.md
  docs/setup/4-web-server.md
  docs/setup/5-logging.md
  docs/setup/6-ldap.md
  docs/setup/7-scheduled-tasks.md
  mkdocs.yml
Labels: type: documentation

#270 correction to the doc
  docs/setup/migrate-to-systemd.md
Labels: type: documentation
