Repository peering-manager/peering-manager, pull requests merged in 2020-05, with the labels that each got.

#239 Add Router IX Peer/Direct Session views
  peering/forms.py
  peering/models.py
  peering/urls.py
  peering/views.py
  templates/peering/router/_base.html
  templates/peering/router/direct_peering_sessions.html
  templates/peering/router/internet_exchange_peering_sessions.html
Labels: type: enhancement

#228 Ui improvements
  peering/forms.py
  peering/models.py
  peering/views.py
Labels: type: enhancement

#249 Use Redis as cache
  .github/workflows/testing.yml
  .gitignore
  docs/configuration/optional-settings.md
  peering/tables.py
  peering/views.py
  peering_manager/configuration.example.py
  peering_manager/settings.py
  requirements.txt
  scripts/development/dev-stack.yml
Labels: type: feature request

#252 Leverage API driven select element
  peering/forms.py
  peering/models.py
  peering/urls.py
  peering/views.py
  peeringdb/forms.py
  project-static/js/forms.js
  templates/peering/as/inc/direct_peering_sessions_table.html
  templates/peering/bgp-group/inc/sessions_table.html
  templates/peering/ix/inc/sessions_table.html
  templates/peering/router/direct_peering_sessions.html
  templates/peering/router/inc/sessions_table.html
  utils/forms.py
  utils/templates/widgets/select_api.html
  utils/views.py
Labels: type: enhancement, type: housekeeping

#254 Closes #199: Per-user preferences
  .gitattributes
  project-static/bootstrap-4.4.1-dist/css/bootstrap-grid.css.map
  project-static/bootstrap-4.4.1-dist/css/bootstrap-grid.min.css
  project-static/bootstrap-4.4.1-dist/css/bootstrap-grid.min.css.map
  project-static/bootstrap-4.4.1-dist/css/bootstrap-reboot.css.map
  project-static/bootstrap-4.4.1-dist/css/bootstrap-reboot.min.css
  project-static/bootstrap-4.4.1-dist/css/bootstrap-reboot.min.css.map
  project-static/bootstrap-4.4.1-dist/css/bootstrap.css.map
  project-static/bootstrap-4.4.1-dist/css/bootstrap.min.css
  project-static/bootstrap-4.4.1-dist/css/bootstrap.min.css.map
  project-static/bootstrap-4.4.1-dist/js/bootstrap.bundle.js.map
  project-static/bootstrap-4.4.1-dist/js/bootstrap.bundle.min.js
  project-static/bootstrap-4.4.1-dist/js/bootstrap.bundle.min.js.map
  project-static/bootstrap-4.4.1-dist/js/bootstrap.js.map
  project-static/bootstrap-4.4.1-dist/js/bootstrap.min.js
  project-static/bootstrap-4.4.1-dist/js/bootstrap.min.js.map
  project-static/bootstrap-4.5.0-dist/css/bootstrap-grid.css
  project-static/bootstrap-4.5.0-dist/css/bootstrap-grid.css.map
  project-static/bootstrap-4.5.0-dist/css/bootstrap-grid.min.css
  project-static/bootstrap-4.5.0-dist/css/bootstrap-grid.min.css.map
  project-static/bootstrap-4.5.0-dist/css/bootstrap-reboot.css
  project-static/bootstrap-4.5.0-dist/css/bootstrap-reboot.css.map
  project-static/bootstrap-4.5.0-dist/css/bootstrap-reboot.min.css
  project-static/bootstrap-4.5.0-dist/css/bootstrap-reboot.min.css.map
  project-static/bootstrap-4.5.0-dist/css/bootstrap.css
  project-static/bootstrap-4.5.0-dist/css/bootstrap.css.map
  project-static/bootstrap-4.5.0-dist/css/bootstrap.min.css
  project-static/bootstrap-4.5.0-dist/css/bootstrap.min.css.map
  project-static/bootstrap-4.5.0-dist/js/bootstrap.bundle.js
  project-static/bootstrap-4.5.0-dist/js/bootstrap.bundle.js.map
  project-static/bootstrap-4.5.0-dist/js/bootstrap.bundle.min.js
  project-static/bootstrap-4.5.0-dist/js/bootstrap.bundle.min.js.map
  project-static/bootstrap-4.5.0-dist/js/bootstrap.js
  project-static/bootstrap-4.5.0-dist/js/bootstrap.js.map
  project-static/bootstrap-4.5.0-dist/js/bootstrap.min.js
  project-static/bootstrap-4.5.0-dist/js/bootstrap.min.js.map
  project-static/css/base.css
  project-static/js/jquery-3.4.1.min.js
  project-static/js/jquery-3.5.0.min.js
  project-static/js/jquery-3.5.1.min.js
  templates/500.html
  templates/_base.html
  templates/users/_user.html
  templates/users/preferences.html
  users/admin.py
  users/migrations/0002_userpreferences.py
  users/models.py
  users/tests/test_models.py
  users/urls.py
  users/views.py
  utils/paginators.py
  utils/views.py
Labels: type: feature request
