Repository peering-manager/peering-manager, pull requests merged in 2021-05, with the labels that each got.

#402 PM-195 - Email Documentation Update
  docs/integration.md
  docs/setup/7-scheduled-tasks.md
Labels: type: documentation

#401 PM-377 - Extend Available Peers Filter
  peeringdb/filters.py
  peeringdb/forms.py
Labels: type: enhancement

#403 Add section about systemd timers instead of cron
  docs/setup/7-scheduled-tasks.md
Labels: type: documentation

#405 Remove "Requirements" section from prometheus documentation
  docs/setup/8-prometheus.md
Labels: type: documentation

#398 Service References
  docs/models/peering/directpeeringsession.md
  docs/models/peering/internetexchangepeeringsession.md
  peering/forms.py
  peering/migrations/0074_auto_20210426_1943.py
  peering/migrations/0075_backfill_service_ref.py
  peering/migrations/0076_auto_20210426_1944.py
  peering/models/abstracts.py
  peering/models/models.py
  peering/tables.py
  templates/peering/directpeeringsession/add_edit.html
  templates/peering/directpeeringsession/details.html
  templates/peering/internetexchangepeeringsession/add_edit.html
  templates/peering/internetexchangepeeringsession/details.html
Labels: type: feature request

#409 Display service_reference via API
  peering/api/serializers.py
Labels: type: enhancement

#391 Jinja2 filters for templates
  .pre-commit-config.yaml
  README.md
  docs/templating/arista-eos.md
  docs/templating/cisco-iosxr.md
  docs/templating/examples/arista-eos.md
  docs/templating/examples/cisco-iosxr.md
  docs/templating/examples/juniper-junos.md
  docs/templating/examples/peering-request-email.md
  docs/templating/filters.md
  docs/templating/index.md
  docs/templating/juniper-junos.md
  docs/templating/variables.md
  mkdocs.yml
  peering/api/views.py
  peering/models/abstracts.py
  peering/models/jinja2.py
  peering/models/mixins.py
  peering/models/models.py
  peering/models/templates.py
  peering/tests/test_jinja2.py
  peering/tests/test_models.py
  peering/views.py
  templates/peering/autonomoussystem/_base.html
  templates/peering/autonomoussystem/inc/direct_peering_sessions_table.html
  templates/peering/configuration/details.html
  templates/peering/email/details.html
  utils/templatetags/helpers.py
Labels: priority: high, type: enhancement

#408 PM-407 - Add Support for PeeringDB API Keys
  docs/configuration/optional-settings.md
  docs/integration.md
  docs/setup/7-scheduled-tasks.md
  peering_manager/settings.py
  peeringdb/sync.py
Labels: type: feature request

#417 Add config context field to Router and RoutingPolicy
  docs/models/peering/configcontexts.md
  docs/models/peering/router.md
  docs/models/peering/routingpolicy.md
  mkdocs.yml
  peering/api/serializers.py
  peering/forms.py
  peering/migrations/0077_add_configcontext.py
  peering/models/models.py
  templates/peering/router/add_edit.html
  templates/peering/router/details.html
  templates/peering/routingpolicy/add_edit.html
  templates/peering/routingpolicy/details.html
Labels: priority: medium, type: feature request

#423 Move doc theme to material
  .readthedocs.yml
  README.md
  docs/index.md
  docs/media/peering-manager.svg
  docs/media/ui/local-as-menu.png
  docs/media/ui/navbar.png
  docs/media/ui/table-config.png
  docs/media/ui/user-menu.png
  docs/requirements.txt
  docs/user-interface.md
  mkdocs.yml
  project-static/img/sponsors/logo_decix.svg
Labels: type: documentation

#432 PM-431 - Fix AutonomousSystem Routing
  peering/views.py
Labels: type: bug
