Repository peering-manager/peering-manager, pull requests merged in 2021-11, with the labels that each got.

#506 Changing NGINX Proxy Configuration in Documentation
  docs/setup/4b-nginx.md
Labels: type: documentation

#509 Handle generator returned by pynetbox
  netbox/api.py
Labels: type: bug, status: accepted

#510 Loop over connections instead of routers
  peering/models/models.py
Labels: type: enhancement, priority: low
