Repository peering-manager/peering-manager, pull requests merged in 2021-06, with the labels that each got.

#438 PM-437 - Traceback when Importing Sessions
  peering/models/models.py
Labels: type: bug

#436 Fix or comment broken documentation links
  CHANGELOG.md
  peering/forms.py
  templates/_base.html
  templates/home.html
  templates/peering/configuration/details.html
  templates/peering/email/details.html
  utils/templatetags/helpers.py
Labels: type: documentation

#442 Allow Connection State Updating
  net/forms.py
Labels: priority: low, type: bug

#444 PM-400 - Import all IX Sessions
  peering/management/commands/import_all_ix_sessions.py
Labels: priority: low, type: enhancement

#443 PM-319 - Add IX Session from ASN
  templates/peering/autonomoussystem/inc/internet_exchange_peering_sessions_table.html
Labels: priority: low, type: enhancement

#445 Expose General Peering Policy from PDB
  docs/models/peering/autonomoussystem.md
  peering/models/models.py
  templates/peering/autonomoussystem/details.html
Labels: priority: low, type: enhancement

#450 Filter out policies that don't match the session IP Family
  peering/models/abstracts.py
Labels: type: enhancement

#458 Cascade Delete Connection from IXP
  net/migrations/0002_alter_connection_internet_exchange_point.py
  net/models.py
  peering/migrations/0071_auto_20210321_1843.py
Labels: priority: medium, type: bug

#439 PM-371 Email Enhancements
  docs/configuration/optional-settings.md
  peering/forms.py
  peering/models/models.py
  peering/tests/test_forms.py
  peering/views.py
  peering_manager/settings.py
  templates/peering/autonomoussystem/email.html
Labels: type: enhancement
