Repository peering-manager/peering-manager, pull requests merged in 2021-02, with the labels that each got.

#357 Modify IX & BGP Slug Warnings
  peering/forms.py
Labels: type: documentation

#353 Router States (Disabled/Enabled/Maintenance)
  peering/api/serializers.py
  peering/api/views.py
  peering/enums.py
  peering/filters.py
  peering/forms.py
  peering/management/commands/configure_routers.py
  peering/migrations/0068_router_device_state.py
  peering/models.py
  peering/tables.py
  peering/tests/test_api.py
  peering/tests/test_filters.py
  peering/tests/test_forms.py
  peering/tests/test_models.py
  peering/tests/test_views.py
  templates/peering/router/add_edit.html
  templates/peering/router/configuration.html
  templates/peering/router/details.html
Labels: type: enhancement

#361 Add `devices` app and `Platform` model
  .pre-commit-config.yaml
  devices/__init__.py
  devices/admin.py
  devices/api/__init__.py
  devices/api/nested_serializers.py
  devices/api/serializers.py
  devices/api/urls.py
  devices/api/views.py
  devices/apps.py
  devices/crypto/__init__.py
  devices/crypto/cisco.py
  devices/crypto/juniper.py
  devices/enums.py
  devices/filters.py
  devices/forms.py
  devices/migrations/0001_initial.py
  devices/migrations/__init__.py
  devices/models.py
  devices/tables.py
  devices/tests/__init__.py
  devices/tests/test_api.py
  devices/tests/test_filters.py
  devices/tests/test_forms.py
  devices/tests/test_models.py
  devices/tests/test_views.py
  devices/urls.py
  devices/views.py
  peering/api/views.py
  peering/enums.py
  peering/filters.py
  peering/forms.py
  peering/migrations/0069_auto_20210212_1850.py
  peering/models.py
  peering/signals.py
  peering/tables.py
  peering/tests/test_api.py
  peering/tests/test_filters.py
  peering/tests/test_forms.py
  peering/tests/test_models.py
  peering/tests/test_views.py
  peering_manager/settings.py
  peering_manager/urls.py
  peering_manager/views.py
  templates/_base.html
  templates/devices/platform/add_edit.html
  templates/devices/platform/list.html
  templates/peering/router/details.html
  tox.ini
Labels: type: feature request
