Repository peering-manager/peering-manager, pull requests merged in 2024-09, with the labels that each got.

#863 fix(documentation): typo in napalm
  docs/integrations/napalm.md
Labels: type: documentation

#867 Add value as searchable on CommunityFilterSet
  peering/filtersets.py
Labels: type: enhancement

#865 Add comments to searchable fields on FilterSet for Direct and InternetExchangePeeringSessions
  peering/filtersets.py
Labels: type: enhancement

#869 Add BFD model
  docs/models/net/bfd.md
  mkdocs.yaml
  net/api/nested_serializers.py
  net/api/serializers/__init__.py
  net/api/serializers/bfd.py
  net/api/serializers/connections.py
  net/api/urls.py
  net/api/views/__init__.py
  net/api/views/bfd.py
  net/api/views/connections.py
  net/filtersets/__init__.py
  net/filtersets/bfd.py
  net/filtersets/connections.py
  net/forms/__init__.py
  net/forms/bfd.py
  net/forms/connections.py
  net/migrations/0011_add_bfd.py
  net/models/__init__.py
  net/models/bfd.py
  net/models/connections.py
  net/tables/__init__.py
  net/tables/bfd.py
  net/tables/connections.py
  net/tests/test_api.py
  net/tests/test_filtersets.py
  net/tests/test_forms.py
  net/tests/test_models.py
  net/tests/test_views.py
  net/urls.py
  net/views/__init__.py
  net/views/bfd.py
  net/views/connections.py
  peering/api/serializers.py
  peering/filtersets.py
  peering/forms.py
  peering/migrations/0103_session_bfd.py
  peering/models/abstracts.py
  peering/tables/tables.py
  peering/tests/test_filtersets.py
  peering_manager/constants.py
  peering_manager/views/misc.py
  templates/_base.html
  templates/home.html
  templates/net/bfd/_base.html
  templates/net/bfd/list.html
  templates/net/bfd/view.html
  templates/peering/directpeeringsession/view.html
  templates/peering/internetexchangepeeringsession/view.html
Labels: type: feature request
