Repository peering-manager/peering-manager, pull requests merged in 2024-10, with the labels that each got.

#871 Fix migration dependencies of router move in peering app
  peering/migrations/0102_move_router.py
Labels: type: bug

#872 Add system views
  core/constants.py
  core/tables/__init__.py
  core/tables/change_logging.py
  core/tables/data.py
  core/tables/jobs.py
  core/tables/tasks.py
  core/urls.py
  core/views/__init__.py
  core/views/system.py
  core/views/tasks.py
  peering_manager/admin.py
  peering_manager/tables/columns.py
  peering_manager/tables/tables.py
  peering_manager/urls.py
  templates/_base-new.html
  templates/_base.html
  templates/admin/index.html
  templates/core/system.html
  templates/core/task/rq_queue_list.html
  templates/core/task/rq_task.html
  templates/core/task/rq_task_list.html
  templates/core/task/worker.html
  templates/core/task/worker_list.html
Labels: type: enhancement, type: feature request

#875 Fix merged_communities on Session-Model for direct peering session
  peering/models/abstracts.py
Labels: type: bug

#876 Fix CI run for PR coming from forks
  .github/workflows/ci.yml
Labels: type: bug, type: housekeeping

#878 Add communities on router model
  devices/api/serializers.py
  devices/forms.py
  devices/migrations/0008_router_communities.py
  devices/models.py
  devices/tables.py
  docs/templating/filters.md
  peering/models/abstracts.py
  templates/devices/router/view.html
Labels: type: feature request

#880 Nokia SROS configuration template example
  docs/templating/examples/nokia-sros.md
  docs/templating/index.md
Labels: type: documentation
